test_that("Map of Black Bullhead works", {

  dat_for_bb = structure(list(DataSource = c("Old BCG AIS layer", "Old BCG AIS layer",
                                             "Old BCG AIS layer", "Old BCG AIS layer", "Old BCG AIS layer"
  ), Species = c("Black Bullhead", "Black Bullhead", "Black Bullhead",
                 "Black Bullhead", "Black Bullhead"), Date = c("1947", "1981",
                                                               "2009-01-01", "NA", "2010-07-13"), Location = c("Dala River",
                                                                                                               "Elk Lake", "Shawnigan Lake", "Bertrand Creek", " "), geometry = structure(list(
                                                                                                                 structure(c(-128.513343881839, 53.8486018979627), class = c("XY",
                                                                                                                                                                             "POINT", "sfg")), structure(c(-123.395832881681, 48.5193751762429
                                                                                                                                                                             ), class = c("XY", "POINT", "sfg")), structure(c(-123.650618338146,
                                                                                                                                                                                                                              48.6446664870025), class = c("XY", "POINT", "sfg")), structure(c(-122.524536512243,
                                                                                                                                                                                                                                                                                               49.0002779741533), class = c("XY", "POINT", "sfg")), structure(c(-122.812323951792,
                                                                                                                                                                                                                                                                                                                                                                49.0977783121835), class = c("XY", "POINT", "sfg"))), class = c("sfc_POINT",
                                                                                                                                                                                                                                                                                                                                                                                                                                "sfc"), precision = 0, bbox = structure(c(xmin = -128.513343881839,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ymin = 48.5193751762429, xmax = -122.524536512243, ymax = 53.8486018979627
                                                                                                                                                                                                                                                                                                                                                                                                                                ), class = "bbox"), crs = structure(list(input = "EPSG:4326",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         wkt = "GEOGCRS[\"WGS 84\",\n    ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n        MEMBER[\"World Geodetic System 1984 (Transit)\"],\n        MEMBER[\"World Geodetic System 1984 (G730)\"],\n        MEMBER[\"World Geodetic System 1984 (G873)\"],\n        MEMBER[\"World Geodetic System 1984 (G1150)\"],\n        MEMBER[\"World Geodetic System 1984 (G1674)\"],\n        MEMBER[\"World Geodetic System 1984 (G1762)\"],\n        MEMBER[\"World Geodetic System 1984 (G2139)\"],\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]],\n        ENSEMBLEACCURACY[2.0]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    USAGE[\n        SCOPE[\"Horizontal component of 3D system.\"],\n        AREA[\"World.\"],\n        BBOX[-90,-180,90,180]],\n    ID[\"EPSG\",4326]]"), class = "crs"), n_empty = 0L),
  Scientific_Name = c(NA_character_, NA_character_, NA_character_,
                      NA_character_, NA_character_)), row.names = c(NA, -5L), sf_column = "geometry", agr = structure(c(DataSource = NA_integer_,
                                                                                                                        Species = NA_integer_, Date = NA_integer_, Location = NA_integer_,
                                                                                                                        Scientific_Name = NA_integer_), class = "factor", levels = c("constant",
                                                                                                                                                                                     "aggregate", "identity")), class = c("sf", "tbl_df", "tbl", "data.frame"
                                                                                                                                                                                     ))
  # expect_equal(2+2,4)

  expect_snapshot(dat_for_bb)
})
